sudo: required
services:
  - docker

script:
  - docker build -t jmchiang/node .
  - docker images jmchiang/node

before_deploy:
  - docker login -u jmchiang -p $docker_pass

deploy:
  provider: script
  script: docker push jmchiang/node
  on:
      branch: master
